trigger:
  branches:
    include:
      - main
  paths:
    include:
      - database-migration

pool:
  vmImage: ubuntu-latest

stages:
  - stage: terraform
    displayName: Checking Infrastructure Configuration
    pool:
      vmImage: "ubuntu-20.04"
    jobs:
      - job: Checking_Plan_for_Infrastructure
        steps:
          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
            displayName: Install Terraform
            inputs:
              terraformVersion: "latest"

          - task: TerraformTaskV3@3
            displayName: Initial Database Migration Script
            inputs:
              provider: "aws"
              command: "init"
              workingDirectory: "$(System.DefaultWorkingDirectory)/database-migration"
              backendServiceAWS: "terraform for aws gtp-nonprd"
              backendAWSBucketName: "tfstate-gtp-nonprod-h85t9r"
              backendAWSKey: "nonprod/build/database-migration/terraform.tfstate"

          - task: TerraformTaskV3@3
            displayName: Check Plan Database Migration Script
            inputs:
              provider: "aws"
              command: "plan"
              workingDirectory: "$(System.DefaultWorkingDirectory)/database-migration"
              environmentServiceNameAWS: "terraform for aws gtp-nonprd"

  - stage: report_arfifact
    displayName: Publish Artifact and Report
    pool:
      vmImage: "ubuntu-20.04"
    jobs:
      - job: database_migration
        steps:
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "database-migration"
              ArtifactName: "database-migration-infra"
              publishLocation: "Container"
